#!/bin/bash

echo "Deploying Complete Shipping Status Solution"
echo "==========================================="

# Upload all the files
echo "Uploading all fixed files..."
scp app/Http/Controllers/SellPosController.php u102957485@digitrot.com:/home/u102957485/domains/digitrot.com/public_html/pos/app/Http/Controllers/
scp public/js/pos.js u102957485@digitrot.com:/home/u102957485/domains/digitrot.com/public_html/pos/public/js/
scp debug_shipping_status_final.php u102957485@digitrot.com:/home/u102957485/domains/digitrot.com/public_html/pos/
scp check_latest_transaction_status.php u102957485@digitrot.com:/home/u102957485/domains/digitrot.com/public_html/pos/

# Clear all caches
echo "Clearing all caches..."
ssh u102957485@digitrot.com "cd /home/u102957485/domains/digitrot.com/public_html/pos && php artisan cache:clear"
ssh u102957485@digitrot.com "cd /home/u102957485/domains/digitrot.com/public_html/pos && php artisan config:clear"
ssh u102957485@digitrot.com "cd /home/u102957485/domains/digitrot.com/public_html/pos && php artisan view:clear"
ssh u102957485@digitrot.com "cd /home/u102957485/domains/digitrot.com/public_html/pos && php artisan route:clear"

echo "Deployment completed!"
echo ""
echo "COMPLETE SOLUTION DEPLOYED"
echo "=========================="
echo ""
echo "Understanding the Issue:"
echo "- The 'Order Status' column in sales table = shipping_status field"
echo "- There is no separate 'order_status' field"
echo "- POS form field 'shipping_status' should update this column"
echo ""
echo "What We Fixed:"
echo "1. JavaScript: Forces shipping_status field inclusion in form"
echo "2. Server: Enhanced validation and logging"
echo "3. Database: Aggressive fix to force correct value"
echo ""
echo "Testing Steps:"
echo "=============="
echo "1. Run final debug script:"
echo "   php debug_shipping_status_final.php"
echo ""
echo "2. Create a POS sale:"
echo "   - Select 'Ready' or 'Delivered' from dropdown"
echo "   - Check browser console for: 'shipping_status=packed'"
echo "   - Complete the sale"
echo ""
echo "3. Check Laravel logs:"
echo "   tail -f storage/logs/laravel.log"
echo "   Look for: 'POS Form Shipping Status Debug'"
echo ""
echo "4. Verify in sales table:"
echo "   - Order Status column should show 'Ready' or 'Delivered'"
echo ""
echo "Expected Mapping:"
echo "================"
echo "POS Dropdown → Database → Display"
echo "Ordered      → ordered   → Ordered"
echo "Ready        → packed    → Ready"
echo "Delivered    → delivered → Delivered"
echo ""
echo "If still not working, the issue may be:"
echo "- Browser caching (hard refresh: Ctrl+F5)"
echo "- Database constraints or triggers"
echo "- Different table being displayed"